### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by BanCrash** [sinanislekdemir/poorman#1]
Hi! I was searching for a tool like this, and I think yours is the best I could use for my needs, but I'm on Windows. Is there any chance of making this run on Windows?

**Comment by sinanislekdemir** [comment]
I can't promise a timeline but I can try to compile it for Windows when I have some free time to bring up a virtual pc. 
I would say in a week time's maybe?

**Comment by sinanislekdemir** [comment]
Okay I'm surprised to see that it went quite straight-forward. 
https://github.com/sinanislekdemir/poorman/releases/download/v1.0.3/PoorMansCatalog_v1.0.3_win64.zip

Please take a test ride and let me know if it works at the first run.
Some graphic elements like the Folder icon at the directory tree does not seem to work for Windows but I guess if I spare more time in it. I can find a workaround. Note that, I'm not a Windows guy, it's been more than a decade since I did something on Windows :D I just had the ISO image and a license that came with my laptop. 
If it works but there are small glitches or bugs, I would appreciate closing this issue and creating new issues. So it can be more visible.

**Comment by BanCrash** [comment]
> Okay I'm surprised to see that it went quite straight-forward. https://github.com/sinanislekdemir/poorman/releases/download/v1.0.3/PoorMansCatalog_v1.0.3_win64.zip
> 
> Please take a test ride and let me know if it works at the first run. Some graphic elements like the Folder icon at the directory tree does not seem to work for Windows but I guess if I spare more time in it. I can find a workaround. Note that, I'm not a Windows guy, it's been more than a decade since I did something on Windows :D I just had the ISO image and a license that came with my laptop. If it works but there are small glitches or bugs, I would appreciate closing this issue and creating new issues. So it can be more visible.

Yep, it's working, it seems that as you said it doesn't show the thumbnails. Nothing important IMO.

Thank you for taking time on doing this version! As you said, if I found bugs I'll open new issues. Thank you again!

**Comment by sinanislekdemir** [comment]
well at least the jpg thumbnails work as expected :) if it can create a thumbnail of an image file, it shows up. also file list thumbnails showed up for me :)
